version: '3.8'
services:
  bot:
    image: bot_image
    build:
      context: ./bot
    restart: always
    depends_on:
      - postgres_primary
    environment:
      TOKEN: ${TOKEN}
      RM_HOST: ${RM_HOST}
      RM_PORT: ${RM_PORT}
      RM_USER: ${RM_USER}
      RM_PASSWORD: ${RM_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
  postgres_primary:
    image: db_image
    build: ./db
    ports:
      - ${DB_PORT}:5432
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "unix_socket_directories=/var/run/postgresql"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "log_replication_commands=on"
      - "-c"
      - "wal_level=replica"
      - "-c"
      - "wal_log_hints=on"
      - "-c"
      - "password_encryption=scram-sha-256"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
    env_file:
      - .env
  postgres_replica:
    image: db_repl_image
    build: ./db_repl
    ports:
      - ${DB_REPL_PORT}:5432
    expose:
      - 5433
    restart: always
    depends_on:
      - postgres_primary
    environment:
      - POSTGRES_USER=${DB_REPL_USER}
      - POSTGRES_PASSWORD=${DB_REPL_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_HOST=${DB_HOST}
